# Generated by Django 5.1.2 on 2024-11-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
