# Generated by Django 5.1.2 on 2024-11-04 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_failed_login_attempts_user_is_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=1,
                max_length=255,
                unique=True,
                validators=[django.core.validators.EmailValidator],
            ),
            preserve_default=False,
        ),
    ]
